// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Work_Dashboard.Data;

#nullable disable

namespace WorkDashboard.Migrations
{
    [DbContext(typeof(BdaDbContext))]
    [Migration("20260508042733_AddAnfAndWorkOrderFields")]
    partial class AddAnfAndWorkOrderFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Work_Dashboard.Data.Entities.AuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int")
                        .HasColumnName("changed_by");

                    b.Property<string>("Details")
                        .HasColumnType("json")
                        .HasColumnName("details");

                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("table_name");

                    b.HasKey("LogId");

                    b.HasIndex("ChangedBy");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.BudgetHead", b =>
                {
                    b.Property<int>("BudgetHeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("budget_head_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BudgetHeadId"));

                    b.Property<decimal>("AmountSpent")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("amount_spent");

                    b.Property<decimal>("AvailableFund")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("available_fund");

                    b.Property<string>("BudgetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("budget_code");

                    b.Property<string>("BudgetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("budget_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("remaining_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("BudgetHeadId");

                    b.HasIndex("BudgetCode")
                        .IsUnique();

                    b.ToTable("budget_head_master", (string)null);
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.Engineer", b =>
                {
                    b.Property<int>("EngineerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("engineer_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EngineerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("EngineerId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("engineers", (string)null);
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.FundSource", b =>
                {
                    b.Property<int>("FundSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fund_source_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FundSourceId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("source_code");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source_name");

                    b.HasKey("FundSourceId");

                    b.HasIndex("SourceCode")
                        .IsUnique();

                    b.ToTable("fund_sources", (string)null);
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.Work", b =>
                {
                    b.Property<int>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("work_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkId"));

                    b.Property<DateOnly?>("ActualCompletion")
                        .HasColumnType("date")
                        .HasColumnName("actual_completion");

                    b.Property<decimal?>("AgreementAmount")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("agreement_amount");

                    b.Property<DateOnly?>("AnfDate")
                        .HasColumnType("date");

                    b.Property<string>("AnfNo")
                        .HasColumnType("longtext");

                    b.Property<int?>("AssignedAenId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_aen_id");

                    b.Property<int?>("AssignedExenId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_exen_id");

                    b.Property<int?>("AssignedJenId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_jen_id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("ContractorMobile")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("contractor_mobile");

                    b.Property<string>("ContractorName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("contractor_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("department");

                    b.Property<DateOnly?>("ExpectedCompletion")
                        .HasColumnType("date")
                        .HasColumnName("expected_completion");

                    b.Property<decimal?>("Expenditure")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("expenditure");

                    b.Property<decimal?>("FinancialProgressPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("financial_progress_percent");

                    b.Property<int?>("FundSourceId")
                        .HasColumnType("int")
                        .HasColumnName("fund_source_id");

                    b.Property<bool>("IsAnnualContract")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_annual_contract");

                    b.Property<bool>("IsCmBudget")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_cm_budget");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsScheme")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_scheme");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("payment_status");

                    b.Property<decimal?>("ProgressPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("progress_percent");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<decimal?>("SanctionedAmount")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("sanctioned_amount");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("WardNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ward_number");

                    b.Property<string>("WorkCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("work_code");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("work_name");

                    b.Property<DateOnly?>("WorkOrderDate")
                        .HasColumnType("date");

                    b.Property<string>("WorkOrderNo")
                        .HasColumnType("longtext");

                    b.HasKey("WorkId");

                    b.HasIndex("AssignedAenId");

                    b.HasIndex("AssignedExenId");

                    b.HasIndex("AssignedJenId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FundSourceId");

                    b.HasIndex("WorkCode")
                        .IsUnique();

                    b.ToTable("works", (string)null);
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.WorkBill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bill_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BillId"));

                    b.Property<DateOnly?>("BillDate")
                        .HasColumnType("date")
                        .HasColumnName("bill_date");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("bill_number");

                    b.Property<int?>("BudgetHeadId")
                        .HasColumnType("int")
                        .HasColumnName("budget_head_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<decimal>("CumulativeBilled")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("cumulative_billed");

                    b.Property<decimal>("Deductions")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("deductions");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("gross_amount");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("net_amount");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("pdf_url");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkId")
                        .HasColumnType("int")
                        .HasColumnName("work_id");

                    b.HasKey("BillId");

                    b.HasIndex("BudgetHeadId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WorkId");

                    b.ToTable("work_bills", (string)null);
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.WorkCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("category_code");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("work_categories", (string)null);
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.WorkFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("file_url");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.Property<int>("WorkId")
                        .HasColumnType("int")
                        .HasColumnName("work_id");

                    b.HasKey("Id");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("WorkId");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.WorkProgressLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("logged_at");

                    b.Property<int?>("LoggedBy")
                        .HasColumnType("int")
                        .HasColumnName("logged_by");

                    b.Property<decimal?>("ProgressPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("progress_percent");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<int>("WorkId")
                        .HasColumnType("int")
                        .HasColumnName("work_id");

                    b.HasKey("LogId");

                    b.HasIndex("LoggedBy");

                    b.HasIndex("WorkId");

                    b.ToTable("work_progress_log", (string)null);
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.WorkRemark", b =>
                {
                    b.Property<int>("RemarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("remark_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RemarkId"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("author_name");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("edited_at");

                    b.Property<int?>("EditedById")
                        .HasColumnType("int")
                        .HasColumnName("edited_by_id");

                    b.Property<string>("EditedByName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("edited_by_name");

                    b.Property<int>("WorkId")
                        .HasColumnType("int")
                        .HasColumnName("work_id");

                    b.HasKey("RemarkId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("WorkId");

                    b.ToTable("work_remarks", (string)null);
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("Work_Dashboard.Data.Entities.Engineer", "ChangedByEngineer")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChangedByEngineer");
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.Work", b =>
                {
                    b.HasOne("Work_Dashboard.Data.Entities.Engineer", "AssignedAen")
                        .WithMany("AenWorks")
                        .HasForeignKey("AssignedAenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Work_Dashboard.Data.Entities.Engineer", "AssignedExen")
                        .WithMany("ExenWorks")
                        .HasForeignKey("AssignedExenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Work_Dashboard.Data.Entities.Engineer", "AssignedJen")
                        .WithMany("JenWorks")
                        .HasForeignKey("AssignedJenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Work_Dashboard.Data.Entities.WorkCategory", "Category")
                        .WithMany("Works")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Work_Dashboard.Data.Entities.Engineer", "CreatedByEngineer")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Work_Dashboard.Data.Entities.FundSource", "FundSource")
                        .WithMany("Works")
                        .HasForeignKey("FundSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedAen");

                    b.Navigation("AssignedExen");

                    b.Navigation("AssignedJen");

                    b.Navigation("Category");

                    b.Navigation("CreatedByEngineer");

                    b.Navigation("FundSource");
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.WorkBill", b =>
                {
                    b.HasOne("Work_Dashboard.Data.Entities.BudgetHead", "BudgetHead")
                        .WithMany()
                        .HasForeignKey("BudgetHeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Work_Dashboard.Data.Entities.Engineer", "CreatedByEngineer")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Work_Dashboard.Data.Entities.Work", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetHead");

                    b.Navigation("CreatedByEngineer");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.WorkFile", b =>
                {
                    b.HasOne("Work_Dashboard.Data.Entities.Engineer", "UploadedByEngineer")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Work_Dashboard.Data.Entities.Work", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadedByEngineer");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.WorkProgressLog", b =>
                {
                    b.HasOne("Work_Dashboard.Data.Entities.Engineer", "LoggedByEngineer")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("LoggedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Work_Dashboard.Data.Entities.Work", "Work")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoggedByEngineer");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.WorkRemark", b =>
                {
                    b.HasOne("Work_Dashboard.Data.Entities.Engineer", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Work_Dashboard.Data.Entities.Work", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.Engineer", b =>
                {
                    b.Navigation("AenWorks");

                    b.Navigation("ExenWorks");

                    b.Navigation("JenWorks");

                    b.Navigation("ProgressLogs");
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.FundSource", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.Work", b =>
                {
                    b.Navigation("ProgressLogs");
                });

            modelBuilder.Entity("Work_Dashboard.Data.Entities.WorkCategory", b =>
                {
                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
